### ISSUE TITLE
Load time + Animations

### ISSUE THREAD

**Issue by Monklite** [practical-solutions/kkh-template#2]
First off, this is a really well-refined theme. Kudos!  

My only gripes are the sliding transition when opening a new page, I would love an option to disable them. I also noticed an unusually long loading time when a new page is visited (the spinning circle thing). I don't have this issue with any other theme; for example, pages load instantly with dokubook and the default theme, is this something that could possibly be looked into?

**Comment by practical-solutions** [comment]
You are right. I will add an option to disable the animation in the configuration in the next days.

**Comment by practical-solutions** [comment]
The "loading time" is due to the css animation delay.

**Comment by Monklite** [comment]
Alright sweet, solving those two issues would be phenomenal. I'll continue to use it and continue to look for bugs and such.  

I'm not too skilled, but I'll do a PR if there's a useful feature I come up with.  

Great work though, this really solves the primary issues with the default theme in my opinion.

**Comment by practical-solutions** [comment]
I added an option to switch on/off the css-animations. Thanks for your feedback!
